dist: xenial
language: python
cache: pip
install: make setup
stages:
  - lint
  - test
  - name: publish
    if: (tag IS present) AND (branch = master)
jobs:
  include:
    - stage: lint
      before_script: pip install black
      script: make lint
      python: '3.7'
    - stage: test
      python: '3.6'
      script: make test
    - stage: test
      python: '3.8'
      script: make test
    - stage: test
      python: '3.9'
      script: make test
    - stage: test
      python: '3.7'
      script: make coverage
      after_success: codecov
    - stage: publish
      python: '3.7'
      script: make publish
